language: php
php:
  - 7.2
  - 7.3

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token=88852689d2b7b3b515595e4c081c697aa7f93b9867151a0c58e08f307ab7afae --format=php-clover coverage.clover
branches:
  only:
    - master
